name: Snyk Code Security Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
  WIF_POOL: 'parksmart-pool'
  WIF_PROVIDER: 'parksmart-provider'

jobs:
  security_scan:
    name: Snyk Code Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL }}/providers/${{ env.WIF_PROVIDER }}'
          service_account: 'github-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - id: 'secrets'
        name: 'Fetch Secrets from GCP Secret Manager'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            SNYK_TOKEN:projects/${{ env.PROJECT_ID }}/secrets/snyk-token/versions/latest

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # Keep '|| true' if you want it to pass while you toggle the Snyk UI organization setting
      - name: Run Snyk Code Scan (SAST)
        run: snyk code test --severity-threshold=high || true
        env:
          SNYK_TOKEN: ${{ steps.secrets.outputs.SNYK_TOKEN }}